// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OdontoKlinika.API.Data;

#nullable disable

namespace OdontoKlinika.Migrations
{
    [DbContext(typeof(OdontoDbContext))]
    partial class OdontoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OdontoKlinika.API.Models.DarboGrafikas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Dirba")
                        .HasColumnType("bit");

                    b.Property<string>("GydytojoId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pabaiga")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PertraukaIki")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PertraukaNuo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pradzia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SavaitesDiena")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DarboGrafikai");
                });

            modelBuilder.Entity("OdontoKlinika.API.Models.DarboIsimtis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("ArDirba")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<string>("GydytojoId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pabaiga")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pradzia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Priezastis")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DarboIsimtys");
                });

            modelBuilder.Entity("OdontoKlinika.API.Models.Procedura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aprasymas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Kaina")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Pavadinimas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VizitasId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VizitasId");

                    b.ToTable("Proceduros");
                });

            modelBuilder.Entity("OdontoKlinika.API.Models.Vartotojas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Amzius")
                        .HasColumnType("int");

                    b.Property<string>("AsmensKodas")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ElPastas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GoogleId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsTwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("KraujoGrupe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pavarde")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SlaptazodisHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefonas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TwoFactorSecret")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vardas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VartotojoTipas")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.HasKey("Id");

                    b.HasIndex("AsmensKodas")
                        .IsUnique();

                    b.ToTable("Vartotojai");

                    b.HasDiscriminator<string>("VartotojoTipas").HasValue("Vartotojas");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("OdontoKlinika.API.Models.Vizitas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Apmoketa")
                        .HasColumnType("bit");

                    b.Property<string>("Busena")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GydytojasId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PabaigosLaikas")
                        .HasColumnType("datetime2");

                    b.Property<int>("PacientasId")
                        .HasColumnType("int");

                    b.Property<string>("Pastabos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PradziosLaikas")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SukurimoData")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("GydytojasId");

                    b.HasIndex("PacientasId");

                    b.ToTable("Vizitai");
                });

            modelBuilder.Entity("Adminas", b =>
                {
                    b.HasBaseType("OdontoKlinika.API.Models.Vartotojas");

                    b.HasDiscriminator().HasValue("Adminas");
                });

            modelBuilder.Entity("OdontoKlinika.API.Models.Gydytojas", b =>
                {
                    b.HasBaseType("OdontoKlinika.API.Models.Vartotojas");

                    b.Property<int>("DarboPatirtisMetais")
                        .HasColumnType("int");

                    b.Property<string>("Specializacija")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Gydytojas");
                });

            modelBuilder.Entity("OdontoKlinika.API.Models.Pacientas", b =>
                {
                    b.HasBaseType("OdontoKlinika.API.Models.Vartotojas");

                    b.HasDiscriminator().HasValue("Pacientas");
                });

            modelBuilder.Entity("OdontoKlinika.API.Models.Procedura", b =>
                {
                    b.HasOne("OdontoKlinika.API.Models.Vizitas", "Vizitas")
                        .WithMany("Proceduros")
                        .HasForeignKey("VizitasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vizitas");
                });

            modelBuilder.Entity("OdontoKlinika.API.Models.Vizitas", b =>
                {
                    b.HasOne("OdontoKlinika.API.Models.Gydytojas", "Gydytojas")
                        .WithMany("Vizitai")
                        .HasForeignKey("GydytojasId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OdontoKlinika.API.Models.Pacientas", "Pacientas")
                        .WithMany("Vizitai")
                        .HasForeignKey("PacientasId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Gydytojas");

                    b.Navigation("Pacientas");
                });

            modelBuilder.Entity("OdontoKlinika.API.Models.Vizitas", b =>
                {
                    b.Navigation("Proceduros");
                });

            modelBuilder.Entity("OdontoKlinika.API.Models.Gydytojas", b =>
                {
                    b.Navigation("Vizitai");
                });

            modelBuilder.Entity("OdontoKlinika.API.Models.Pacientas", b =>
                {
                    b.Navigation("Vizitai");
                });
#pragma warning restore 612, 618
        }
    }
}
